### ISSUE TITLE
添加手机号码验证

### ISSUE THREAD

**Issue by jhonny-me** [RescueKing/RescueKing-Web#13]

**Comment by codeLockers** [comment]
@jhonny-me 手机号码的正则是11位0～9的数字，第一位是1

**Comment by jhonny-me** [comment]
附上最新的正则链接： https://github.com/VincentSit/ChinaMobilePhoneNumberRegex

**Comment by codeLockers** [comment]
@jhonny-me 已修改

**Comment by jhonny-me** [comment]
@codeLockers 看一看其他issues吧，可以把github的邮箱通知开了，这样通知比较快。

**Comment by codeLockers** [comment]
@jhonny-me 邮件通知有的，有的时候通知有延迟
