### ISSUE TITLE
添加地理位置选择功能

### ISSUE THREAD

**Issue by jhonny-me** [RescueKing/RescueKing-Web#3]

**Comment by jhonny-me** [comment]
Questions：
1. 需不需要地图选择的功能
2. 选择完成后，显示什么？坐标还是地址
3. 数据库保存什么，坐标还是地址，还是两个

@codeLockers

**Comment by codeLockers** [comment]
@jhonny-me 目前感觉地图的使用意义不是很大，可能具体的街道层让用户输入更加精准，这样数据库保存的话只需要地址就行了

**Comment by jhonny-me** [comment]
所以是提供：
**城市**
**区**
的选择，并且留textfield给街道详细地址的填写？

example:
__Suzhou__ __Yuanqu__ ______

还是直接一个field让用户填写。 @codeLockers

**Comment by codeLockers** [comment]
我觉得城市和区提供选择比较好 @jhonny-me

**Comment by jhonny-me** [comment]
功能需求整理如下：

- [ ] 不可选的省份选项（默认江苏省）
- [ ] 可选 *城市* *区*
- [ ] 填写 *街道*
- [ ] 全国省市配置列表

**Comment by jhonny-me** [comment]
找到的配置列表，我们可以先只用江苏省。
[省地县.txt](https://github.com/RescueKing/RescueKing-Web/files/570824/default.txt)

**Comment by jhonny-me** [comment]
not finished, moving to sprint 3

**Comment by jhonny-me** [comment]
done. closing
