### ISSUE TITLE
添加响应式布局

### ISSUE THREAD

**Issue by jhonny-me** [RescueKing/RescueKing-Web#6]

**Comment by jhonny-me** [comment]
界面使用material UI: http://www.material-ui.com/#/get-started/required-knowledge

**Comment by jhonny-me** [comment]
@codeLockers 验证一下：https://rescueking.herokuapp.com/makePost

**Comment by codeLockers** [comment]
@jhonny-me 目前我们现在先做web还是后台？我目前学习速度可能一时半会跟不上进度

**Comment by jhonny-me** [comment]
@codeLockers 先做web，我的建议是你直接看微信相关的。这些就别管了，不需要重复学习。

**Comment by codeLockers** [comment]
@jhonny-me 就是Reactjs和微信开放平台吗？

**Comment by jhonny-me** [comment]
@codeLockers  目前只需要看一下微信的公众号搭建，菜单页面什么的，最后直接链接到写好的这个页面。时间多于你可以多看看后端，前端东西太多，不建议自己看。

**Comment by jhonny-me** [comment]
closing

**Comment by jhonny-me** [comment]
@codeLockers 不错的学习css的网站: http://zh.learnlayout.com/margin-auto.html
